{
 "title": "Namespace View",
 "description": "Namespace Overveiw dashboard helps visualise multiple namespaces in multiple clusters and their metrics with a focus on resources in the namespaces.",
 "tags": [
  "Monitoring",
  "Namespace"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace - $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "namespace",
   "collapsed": true,
   "panels": [
    {
     "title": "Aerospike Version",
     "type": "stat",
     "description": "Build version of Aerospike Server running in selected cluster across all nodes and namespaces",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "count_values by (build) (\"build_numbers\", (aerospike_node_up{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) )",
       "legendFormat": "{{build}}"
      }
     ]
    },
    {
     "title": "Alerts",
     "type": "piechart",
     "description": "Displays alerts by severity ( critical, error, warn and info)",
     "gridPos": { "h": 7, "w": 4, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (severity) (ALERTS{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace\", severity=~\"warn|critical|info|error\"}) ",
       "legendFormat": "{{severity}}"
      }
     ]
    },
    {
     "title": "Stop Writes / HWM breached (total)",
     "type": "stat",
     "description": "Displays sum of namespace stop_writes, clock skew stop writes and high water mark breached flags across all the nodes and namespaces in selected cluster, a positive value means some issue with resource utilization or configurations ",
     "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_stop_writes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Stop Writes"
      },
      {
       "expr": "sum(aerospike_namespace_clock_skew_stop_writes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Clock Skew Stop Writes"
      },
      {
       "expr": "sum(aerospike_namespace_hwm_breached{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "HWM Breached"
      }
     ]
    },
    {
     "title": "Partitions (total)",
     "type": "stat",
     "description": "Namespace dead or unavailable partitions",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_dead_partitions{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Dead"
      },
      {
       "expr": "sum(aerospike_namespace_unavailable_partitions{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Unavailable"
      }
     ]
    },
    {
     "title": "Read Errors (total)",
     "type": "stat",
     "description": "read errors from file/device",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (storage_engine) (aerospike_namespace_storage_engine_file_read_errors{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{storage_engine}}"
      }
     ]
    },
    {
     "title": "Migrations (total)",
     "type": "stat",
     "description": "Displays sum of partitions Remaining and Active which are Received or Transmitted across selected cluster for the selected nodes and namespaces",
     "gridPos": { "h": 3, "w": 14, "x": 10, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (aerospike_namespace_migrate_rx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_rx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": "RX Remaining"
      },
      {
       "expr": "sum (aerospike_namespace_migrate_rx_partitions_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": "RX Active "
      },
      {
       "expr": "sum (aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": " TX Remaining"
      },
      {
       "expr": "sum (aerospike_namespace_migrate_tx_partitions_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
       "legendFormat": " TX Active"
      }
     ]
    },
    {
     "title": "Data (bytes) (total)",
     "type": "stat",
     "description": "Displays sum of all device or memory used by data (without index) and the sum of allocated bytes",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\n) ",
       "legendFormat": "Used (Device/PMEM) (pre 7x)"
      },
      {
       "expr": "sum(aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_pmem_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(aerospike_namespace_data_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Index (bytes) (total)",
     "type": "stat",
     "description": "Displays sum of all device or memory used by index, sindex and set-index",
     "gridPos": { "h": 4, "w": 10, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_memory_used_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Primary - Memory Used (pre 7x)"
      },
      {
       "expr": "sum(aerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sindex - Memory Used (pre 7x)"
      },
      {
       "expr": "sum(aerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Set - Memory Used (pre 7x)"
      },
      {
       "expr": "sum(aerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Primary - Pmem Used (pre 7x)"
      },
      {
       "expr": "sum(aerospike_namespace_sindex_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sindex - Pmem Used (pre 7x)"
      },
      {
       "expr": "sum(aerospike_namespace_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Primary - Used"
      },
      {
       "expr": "sum(aerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Sindex - Used"
      },
      {
       "expr": "sum(aerospike_namespace_set_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Set - Used"
      },
      {
       "expr": "sum(aerospike_namespace_indexes_memory_budget{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Index (Flash) alloc (bytes) (total)",
     "type": "stat",
     "description": "Flash Alloc Bytes - Total bytes allocated on the mount(s) for the primary index used by this namespace on this node. This statistic represents entire 4KiB chunks which have at least one element in use.\n\n\nFlash Alloc Percent - Percentage of the mount(s) allocated for the primary index used by this namespace on this node. Calculated as (index_flash_alloc_bytes / index-type.mounts-size-limit) * 100. This statistic represents entire 4KiB chunks which have at least one element in use.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_index_flash_alloc_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Allocated Bytes"
      }
     ]
    },
    {
     "title": "Data used (bytes)",
     "type": "bargauge",
     "description": "Displays minimum, average and maximum of all device or memory used by data (without index) across all namespaces",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} or \naerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Min"
      },
      {
       "expr": "avg(aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} or \naerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      },
      {
       "expr": "max(aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} or \naerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Max"
      },
      {
       "expr": "min(aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Min"
      },
      {
       "expr": "avg(aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Avg"
      },
      {
       "expr": "max(aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "% Data used",
     "type": "bargauge",
     "description": "Displays minimum , average  and maximum  device or memory used % by data (without index) ",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min( (100-aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) or (100-aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )\n)",
       "legendFormat": "Min. Device/PMEM"
      },
      {
       "expr": "avg( (100-aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) or (100-aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )\n)",
       "legendFormat": "Avg. Device/PMEM"
      },
      {
       "expr": "avg( (100-aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) or (100-aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )\n)",
       "legendFormat": "Max. Device/PMEM"
      },
      {
       "expr": "min( (aerospike_namespace_data_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) \n)",
       "legendFormat": "Min"
      },
      {
       "expr": "avg( (aerospike_namespace_data_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) \n)",
       "legendFormat": "Avg"
      },
      {
       "expr": "Max( (aerospike_namespace_data_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) \n)",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Index used (bytes)",
     "type": "bargauge",
     "description": "Displays minimum, average and maximum device or memory used by index, sindex and set-index across all namespaces",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(\naerospike_namespace_memory_used_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
       "legendFormat": "Min. "
      },
      {
       "expr": "avg(\naerospike_namespace_memory_used_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
       "legendFormat": "Avg"
      },
      {
       "expr": "max(\naerospike_namespace_memory_used_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
       "legendFormat": "Max"
      },
      {
       "expr": "min(\naerospike_namespace_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_set_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
       "legendFormat": "Min"
      },
      {
       "expr": "avg(\naerospike_namespace_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_set_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
       "legendFormat": "Avg"
      },
      {
       "expr": "max(\naerospike_namespace_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_set_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "% Index Used",
     "type": "bargauge",
     "description": "Displays minimum, maximum, average of all device or memory used by index, sindex and set-index",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(\naerospike_namespace_indexes_memory_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Min"
      },
      {
       "expr": "avg(\naerospike_namespace_indexes_memory_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      },
      {
       "expr": "max(\naerospike_namespace_indexes_memory_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Index (Flash) alloc (bytes)",
     "type": "bargauge",
     "description": "Flash Alloc Bytes - Total bytes allocated on the mount(s) for the primary index used by this namespace on this node. This statistic represents entire 4KiB chunks which have at least one element in use.\n\n\nFlash Alloc Percent - Percentage of the mount(s) allocated for the primary index used by this namespace on this node. Calculated as (index_flash_alloc_bytes / index-type.mounts-size-limit) * 100. This statistic represents entire 4KiB chunks which have at least one element in use.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(aerospike_namespace_index_flash_alloc_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Min"
      },
      {
       "expr": "avg(aerospike_namespace_index_flash_alloc_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      },
      {
       "expr": "max(aerospike_namespace_index_flash_alloc_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Objects per Sprig (Primary Index)",
     "type": "stat",
     "description": "Displays Average objects per sprig in each Namespace, formula is: (master_objects/4096) / partition_tree_sprigs.\npartition_tree_springs default value is 256",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_master_objects {job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}) / 4096\n/ \nmin(aerospike_namespace_partition_tree_sprigs{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\",ns=~\"$namespace|$^\"}!=0)\n",
       "legendFormat": "Min"
      }
     ]
    },
    {
     "title": "Master Objects (total)",
     "type": "stat",
     "description": "Namespace objects (tombstones, master_objects, prole_objects, evicted_objects)",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Master"
      }
     ]
    },
    {
     "title": "% NSUP Cycle deleted",
     "type": "bargauge",
     "description": "Namespace Supervisor (NSUP) Metrics",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(aerospike_namespace_nsup_cycle_deleted_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Min "
      },
      {
       "expr": "avg(aerospike_namespace_nsup_cycle_deleted_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg"
      },
      {
       "expr": "max(aerospike_namespace_nsup_cycle_deleted_pct{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Defrag Sleep (Unique Values)",
     "type": "stat",
     "description": "This shows the unique Defrag Sleep values across nodes\nNOTE: If multiple values are shown mean `defrag_lwm_pct` is configured differently across nodes",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_values(\"defrag_sleep\", (aerospike_namespace_storage_engine_defrag_sleep{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or on() vector(-1) )) ",
       "legendFormat": "{{defrag_sleep}}"
      }
     ]
    },
    {
     "title": "6.x Memory (deprecated) (bytes) (total)",
     "type": "stat",
     "description": "Displays sum of storage memory used by data (without index) across all the namespaces, \n<pre>\nNOTE: this panel is deprecated from 7.0 onwards as this metric is merged into common data metrics\n</pre>",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(aerospike_namespace_memory_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} unless (aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} ) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(aerospike_namespace_memory_size{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\nunless (aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "% Set Quota Used (topk)",
     "type": "bargauge",
     "description": "Set Quota usage against \"stop write size\" configuration",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(3,sort_desc((\n  (aerospike_sets_memory_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}+aerospike_sets_device_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n  /(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}!=0) )*100))",
       "legendFormat": "{{service}}/{{set}}"
      },
      {
       "expr": "topk( 3, sort_desc((\n  (aerospike_sets_data_used_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n  /(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}!=0) )*100) )",
       "legendFormat": "{{service}}/{{set}}"
      }
     ]
    },
    {
     "title": "Master Objects",
     "type": "bargauge",
     "description": "Namespace objects (tombstones, master_objects, prole_objects, evicted_objects)",
     "gridPos": { "h": 4, "w": 4, "x": 7, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Min"
      },
      {
       "expr": "avg(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg."
      },
      {
       "expr": "max(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "NSUP Cycle duration",
     "type": "bargauge",
     "description": "Namespace Supervisor (NSUP) Metrics",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(aerospike_namespace_nsup_cycle_duration{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Min "
      },
      {
       "expr": "avg(aerospike_namespace_nsup_cycle_duration{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Avg "
      },
      {
       "expr": "max(aerospike_namespace_nsup_cycle_duration{cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "Max "
      }
     ]
    },
    {
     "title": "Defrag Low Water Mark (Unique Values)",
     "type": "stat",
     "description": "This shows the unique Defrag Low Water Mark across the nodes, \nNOTE: If multiple values are shown mean `defrag_lwm_pct` is configured differently across nodes",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count_values(\"defrag_lwm_pct\",(aerospike_namespace_storage_engine_defrag_lwm_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or on() vector(-1) )) ",
       "legendFormat": "{{set}}"
      }
     ]
    },
    {
     "title": "6.x % Memory free(deprecated)",
     "type": "bargauge",
     "description": "Displays minimuim, average and maximum memory available for storage across all the namespaces, \n<pre>\nNOTE: this panel is deprecated from 7.0 onwards as this metric is merged into common data metrics\n</pre>",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\nunless (aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )\n)",
       "legendFormat": "Min"
      },
      {
       "expr": "avg(aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\nunless (aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )\n)",
       "legendFormat": "Avg"
      },
      {
       "expr": "max(aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\nunless (aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )\n)",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Migrations (Partitions)",
     "type": "timeseries",
     "description": "Namespace migrate_tx_partitions_remaining (transmit) and migrate_rx_partitions_remaining (receive)\nrx_partitions_active and\ntx_partitions_active",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_migrate_rx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}} : Incoming "
      },
      {
       "expr": "(aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}} : Outgoing "
      },
      {
       "expr": "aerospike_namespace_migrate_rx_partitions_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}} : RX Active"
      },
      {
       "expr": "aerospike_namespace_migrate_tx_partitions_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}} : RX Active"
      },
      {
       "expr": "aerospike_namespace_migrate_fresh_partitions{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}} : Fresh"
      }
     ]
    },
    {
     "title": "Migration Fresh (Partitions)",
     "type": "timeseries",
     "description": "Namespace migrate_tx_partitions_remaining (transmit) and migrate_rx_partitions_remaining (receive)\nrx_partitions_active and\ntx_partitions_active",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_migrate_fresh_partitions{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{storage_engine}} "
      }
     ]
    },
    {
     "title": "Read Errors (total) (rate)",
     "type": "timeseries",
     "description": "Namespace migrate_tx_partitions_remaining (transmit) and migrate_rx_partitions_remaining (receive)\nrx_partitions_active and\ntx_partitions_active",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (service, storage_engine) (rate(aerospike_namespace_storage_engine_file_read_errors{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval] ))",
       "legendFormat": "{{service}} : {{storage_engine}} "
      }
     ]
    },
    {
     "title": "Auto Revived (Partitions)",
     "type": "timeseries",
     "description": "Namespace migrate_tx_partitions_remaining (transmit) and migrate_rx_partitions_remaining (receive)\nrx_partitions_active and\ntx_partitions_active",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_auto_revived_partitions{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{storage_engine}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Defrag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Defrag Q (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(\nrate(aerospike_namespace_storage_engine_file_defrag_q{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) \nor \nrate(aerospike_namespace_storage_engine_device_defrag_q{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\nor \nrate(aerospike_namespace_storage_engine_stripe_defrag_q{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}}/{{ns}} : Q"
      }
     ]
    },
    {
     "title": "Defrag reads & writes (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(\nrate(aerospike_namespace_storage_engine_file_defrag_reads{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])  \nor \nrate(aerospike_namespace_storage_engine_device_defrag_reads{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\nor \nrate(aerospike_namespace_storage_engine_stripe_defrag_reads{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}}//{{ns}} - Reads"
      },
      {
       "expr": " (\nrate(aerospike_namespace_storage_engine_file_defrag_writes{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) \nor \nrate(aerospike_namespace_storage_engine_device_defrag_writes{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\nor \nrate(aerospike_namespace_storage_engine_stripe_defrag_writes{job=~\"$job_name|$^\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])\n)",
       "legendFormat": "{{service}}/{{ns}} - Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput (Read, Write)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Reads (TPS) (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in\n\n1. Total reads = client_read_success + client_read_error + client_read_timeout + client_read_not_found + batch_sub_read_success + batch_sub_read_error + batch_sub_read_timeout + batch_sub_read_not_found\n2. Successful reads = client_read_success + batch_sub_read_success\n3. Errored reads = client_read_error + batch_sub_read_error\n4. Timedout reads = client_read_timeout + batch_sub_read_timeout\n5. Not found = client_read_not_found + batch_sub_not_found",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_client_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Total"
      },
      {
       "expr": "rate(aerospike_namespace_client_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Successful"
      },
      {
       "expr": "rate(aerospike_namespace_client_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_client_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      },
      {
       "expr": "rate(aerospike_namespace_client_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Not Found"
      }
     ]
    },
    {
     "title": "Client Writes (TPS) (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in\n\n1. Total writes = client_write_success + client_write_error + client_write_timeout + batch_sub_write_success + batch_sub_write_error + batch_sub_write_timeout\n2. Successful writes = client_write_success + batch_sub_write_success\n3. Errored writes = client_write_error + batch_sub_write_error\n4. Timedout writes = client_write_timeout + batch_sub_write_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_client_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Total"
      },
      {
       "expr": "rate(aerospike_namespace_client_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Successful"
      },
      {
       "expr": "rate(aerospike_namespace_client_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      },
      {
       "expr": "rate(aerospike_namespace_client_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput (Batch, Query, UDF)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch Sub Transactions (TPS) (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch transactions",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_delete_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_udf_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_delete_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_udf_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Not Found"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_delete_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_udf_filtered_out{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Filtered Out"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_delete_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_delete_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Queries (TPS) (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in total queries.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
      }
     ]
    },
    {
     "title": "UDFs (TPS) (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in \n\n1. Total = client_udf_complete + client_udf_timeout + client_udf_error\n2. Successful = client_udf_complete\n3. Error = client_udf_error\n4. Timeout = client_udf_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_client_udf_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+\nrate(aerospike_namespace_client_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+\nrate(aerospike_namespace_client_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Total"
      },
      {
       "expr": "rate(aerospike_namespace_client_udf_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Successful"
      },
      {
       "expr": "rate(aerospike_namespace_client_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_client_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Objects",
     "type": "timeseries",
     "description": "Namespace master objects",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Master Tombstones",
     "type": "timeseries",
     "description": "Namespace master tombstones",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": " (aerospike_namespace_master_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Evicted Objects",
     "type": "timeseries",
     "description": "Namespace evicted objects",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_evicted_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Expired Objects",
     "type": "timeseries",
     "description": "Namespace expired objects",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_expired_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Non-Replica Tombstones",
     "type": "timeseries",
     "description": "Namespace non-replica tombstones",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_non_replica_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Non-Replica Objects",
     "type": "timeseries",
     "description": "Namespace non-replica objects",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_non_replica_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}} {{ns}}"
      }
     ]
    },
    {
     "title": "Prole Tombstones",
     "type": "timeseries",
     "description": "Namespace replica tombstones",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_prole_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Prole Objects",
     "type": "timeseries",
     "description": "Namespace replica objects",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_prole_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})  ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "XDR Tombstones",
     "type": "timeseries",
     "description": "Number of tombstones which are created by XDR for non-durable client deletes. This includes both master and prole.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_xdr_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "XDR Bin Cemeteries",
     "type": "timeseries",
     "description": "Number of tombstones with bin-tombstones. They are generated when bin convergence is enabled and a record is durably deleted.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_xdr_bin_cemeteries{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MRT Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Monitors Active",
     "type": "timeseries",
     "description": "mrt monitors active",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "(aerospike_namespace_mrt_monitors_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Commit (rate)",
     "type": "timeseries",
     "description": "mrt roll forward success, error, timeout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_mrt_roll_forward_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_mrt_roll_forward_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_mrt_roll_forward_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Rollback (rate)",
     "type": "timeseries",
     "description": "mrt roll back success, error, timeout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_mrt_roll_back_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_mrt_roll_back_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_mrt_roll_back_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Monitor Commit (rate)",
     "type": "timeseries",
     "description": "mrt monitor roll forward success, error, timeout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 111 },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_mrt_monitor_roll_forward_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_mrt_monitor_roll_forward_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_mrt_monitor_roll_forward_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Monitor Rollback (rate)",
     "type": "timeseries",
     "description": "mrt monitor roll back success, error, timeout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_mrt_monitor_roll_back_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_mrt_monitor_roll_back_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_mrt_monitor_roll_back_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Verify (rate)",
     "type": "timeseries",
     "description": "mrt verify read success, error timeout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 117 },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_mrt_verify_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_mrt_verify_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_mrt_verify_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Provisionals",
     "type": "timeseries",
     "description": "mrt provisionals",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 123 },
     "targets": [
      {
       "expr": "(aerospike_namespace_mrt_provisionals{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Fail (rate)",
     "type": "timeseries",
     "description": "fail mrt version mismatch, mrt blocked",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 123 },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_fail_mrt_version_mismatch{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Version Mismatch"
      },
      {
       "expr": "rate(aerospike_namespace_fail_mrt_blocked{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Blocked"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Data trend",
     "type": "timeseries",
     "description": "Namespace device usage trend",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(100-aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}}: Used"
      },
      {
       "expr": "(aerospike_namespace_device_available_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}}: Available "
      },
      {
       "expr": "(aerospike_namespace_high_water_disk_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}}: HWM %"
      },
      {
       "expr": "(aerospike_namespace_data_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}}: Used"
      },
      {
       "expr": "(aerospike_namespace_data_avail_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}}: Available"
      },
      {
       "expr": "(aerospike_namespace_storage_engine_evict_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}}: Evict Used"
      },
      {
       "expr": "(aerospike_namespace_storage_engine_stop_writes_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}: Stop Writes Used %"
      }
     ]
    },
    {
     "title": "6.x % Memory trend (deprecated)",
     "type": "timeseries",
     "description": "Namespace memory trend (Used % vs HWM %)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(100-aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}} : Used"
      },
      {
       "expr": "(aerospike_namespace_high_water_memory_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}}: HWM %"
      },
      {
       "expr": "(aerospike_namespace_stop_writes_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}}: Stop Writes %"
      }
     ]
    },
    {
     "title": "% Data free",
     "type": "timeseries",
     "description": "Namespace storage free percentage (device_free_pct or pmem_free_pct)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} : device"
      },
      {
       "expr": "aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} : pmem"
      },
      {
       "expr": "(100-aerospike_namespace_data_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
       "legendFormat": "{{service}}/{{ns}} : {{storage_engine}}"
      }
     ]
    },
    {
     "title": "% Memory free (deprecated)",
     "type": "timeseries",
     "description": "Namespace memory_free_pct (available namespace memory percentage), high_water_memory_pct (memory high water mark), stop_writes_pct (stop writes threshold)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}}: Free"
      },
      {
       "expr": "aerospike_namespace_high_water_memory_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}}: HWM"
      },
      {
       "expr": "aerospike_namespace_stop_writes_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}}: Stop Writes"
      }
     ]
    },
    {
     "title": "Data used (bytes)",
     "type": "timeseries",
     "description": "Namespace storage usage in bytes (device_used_bytes or pmem_used_bytes)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} : device"
      },
      {
       "expr": "aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} : pmem"
      },
      {
       "expr": "aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} : {{storage_engine}}"
      }
     ]
    },
    {
     "title": "Memory used (deprecated) (bytes)",
     "type": "timeseries",
     "description": "Namespace memory_used_bytes (memory_used_data_bytes (Data) + memory_used_index_bytes (Primary Index) + memory_used_sindex_bytes (Secondary Index))",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_namespace_memory_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} : Used"
      }
     ]
    },
    {
     "title": "Data free (bytes)",
     "type": "timeseries",
     "description": "Namespace storage free bytes (device_total_bytes - device_used_bytes or pmem_total_bytes - pmem_used_bytes)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} : device "
      },
      {
       "expr": "aerospike_namespace_pmem_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}} : pmem"
      },
      {
       "expr": "aerospike_namespace_data_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Memory free (deprecated) (bytes)",
     "type": "timeseries",
     "description": "Namespace free memory = memory_size - memory_used_bytes",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aerospike_namespace_memory_size{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} - aerospike_namespace_memory_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Secondary Index used (bytes)",
     "type": "timeseries",
     "description": "Namespace memory_used_sindex_bytes (Secondary Index)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      },
      {
       "expr": "(aerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Set Index used (bytes)",
     "type": "timeseries",
     "description": "Amount of memory occupied by set indexes for this namespace on this node.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(aerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      },
      {
       "expr": "(aerospike_namespace_set_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) ",
       "legendFormat": "{{service}}/{{ns}}"
      }
     ]
    },
    {
     "title": "Failure rate",
     "type": "timeseries",
     "description": "Namespace fail_generation (Errors due to generation mismatch), fail_key_busy (Hotkey errors), fail_record_too_big (Errors due to record being more that write block size), fail_xdr_forbidden (Forbidden errors due to XDR configs for incoming XDR traffic)\n\nfail_client_lost_conflict - Number of client write transactions (non-xdr) that failed because some bin's last-update-time is greater than the transaction time. This can happen only when the XDR's bin convergence feature is enabled.\n\nfail_xdr_lost_conflict - Number of XDR write transactions that did not succeed in updating all the attempted bins. Only a subset of bin updates might have failed or all the bin updates might have failed.This can happen only when the XDR's bin convergence feature is enabled.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_fail_generation{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Fail Generation"
      },
      {
       "expr": "rate(aerospike_namespace_fail_key_busy{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Key Busy"
      },
      {
       "expr": "rate(aerospike_namespace_fail_record_too_big{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Record Too Big"
      },
      {
       "expr": "rate(aerospike_namespace_fail_client_lost_conflict{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Client Fail Lost Conflict"
      },
      {
       "expr": "rate(aerospike_namespace_fail_xdr_forbidden{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: XDR Forbidden"
      },
      {
       "expr": "rate(aerospike_namespace_fail_xdr_key_busy{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: XDR Fail Key Busy"
      },
      {
       "expr": "rate(aerospike_namespace_fail_xdr_lost_conflict{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: XDR Fail Lost Conflict"
      },
      {
       "expr": "rate(aerospike_namespace_nsup_xdr_key_busy{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: NSUP XDR Key Busy"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch Sub reads (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_read_success, batch_sub_read_not_found, batch_sub_read_error and batch_sub_read_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Not Found"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_read_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Batch Sub writes (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_write_success, batch_sub_write_not_found, batch_sub_write_error and batch_sub_write_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_write_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Not Found"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Batch Sub deletes (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_delete_success, batch_sub_delete_not_found, batch_sub_delete_error and batch_sub_delete_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_delete_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_delete_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Not Found"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_delete_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_delete_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Batch Sub UDF (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_udf_success, batch_sub_udf_not_found, batch_sub_udf_error and batch_sub_udf_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_udf_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_udf_not_found{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Not Found"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_udf_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_udf_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "Batch Sub TSVC (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in batch_sub_tsvc_error, batch_sub_tsvc_timeout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_batch_sub_tsvc_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      },
      {
       "expr": "rate(aerospike_namespace_batch_sub_tsvc_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      }
     ]
    }
   ]
  },
  {
   "title": "Pindex Query Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "All PI queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in primary index queries.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
      }
     ]
    },
    {
     "title": "PI Aggregate queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in primary index aggregate queries.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_pi_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort"
      }
     ]
    },
    {
     "title": "PI Basic Queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in primary index basic queries.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_pi_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
      }
     ]
    },
    {
     "title": "PI OPS BG queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in primary background OPs queries.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_pi_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
      }
     ]
    },
    {
     "title": "PI Basic Short queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in primary index basic short queries.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_pi_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "PI UDF BG queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in primary index background UDF queries.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_pi_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
      }
     ]
    },
    {
     "title": "PI Basic Long queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in primary index basic long queries.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_pi_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort"
      }
     ]
    }
   ]
  },
  {
   "title": "Sindex Query Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "All SI queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in secondary index queries.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
      }
     ]
    },
    {
     "title": "SI Aggregate queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in secondary index aggregate queries.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_aggr_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_aggr_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_aggr_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort"
      }
     ]
    },
    {
     "title": "SI Basic queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in secondary index basic queries.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_si_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort/Timeout"
      }
     ]
    },
    {
     "title": "SI UDF BG queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in secondary index background UDF queries.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_udf_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_udf_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_udf_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort"
      }
     ]
    },
    {
     "title": "SI Basic Short queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in secondary index basic short queries.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_short_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_short_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_short_basic_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Timeout"
      }
     ]
    },
    {
     "title": "SI OPS BG queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in secondary index background OPs queries.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_ops_bg_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_ops_bg_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_ops_bg_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort"
      }
     ]
    },
    {
     "title": "SI Basic Long queries (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in secondary index basic long queries.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_complete{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Success"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Error"
      },
      {
       "expr": "rate(aerospike_namespace_si_query_long_basic_abort{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])",
       "legendFormat": "{{service}}/{{ns}}: Abort"
      }
     ]
    }
   ]
  },
  {
   "title": "Sindex Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sindex GC cleaned (rate)",
     "type": "timeseries",
     "description": "Shows per-second average rate of increase in secondary index garbage collection.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(aerospike_namespace_sindex_gc_cleaned{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])) by (job,cluster_name,ns)",
       "legendFormat": "{{ns}}: "
      }
     ]
    }
   ]
  }
 ]
}