{
 "title": "Set Dashboard",
 "description": "Set dashboard provides specific set level metrics as well as helping in tracking and setting specific set quotas.",
 "tags": [ "set" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   },
   {
    "name": "set",
    "query": {
     "query": "label_values({__name__=~\"aerospike_sets_data_used_bytes|aerospike_sets_memory_data_bytes\", ns=~\"$namespace\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },set)"
    }
   },
   { "name": "set_quota_topk", "label": "Set Quota TopK", "query": "3" }
  ]
 },
 "panels": [
  { "title": "Set: $set", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "set" },
  {
   "title": "Aerospike Version",
   "type": "stat",
   "description": "Build version",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "count_values by (build) (\"build_numbers\", (aerospike_node_up{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}) )",
     "legendFormat": "{{build}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "piechart",
   "description": "Alert count",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (severity) (ALERTS{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\", severity=~\"warn|critical|info|error\", set=~\"$set\",}) ",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Disable Eviction (Unique values)",
   "type": "stat",
   "description": "More details about [disable eviction](https://docs.aerospike.com/reference/configuration#disable-eviction).",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"dis_evict\", (aerospike_sets_disable_eviction{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\",} or on() vector(-1)))",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Stop Writes Count (Unique values)",
   "type": "stat",
   "description": "More details about [stop writes count](https://docs.aerospike.com/reference/configuration#stop-writes-count).",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"stop_write_cnt\",aerospike_sets_stop_writes_count{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\",}>0)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Enable index (Unique values)",
   "type": "stat",
   "description": "More details about [enable index](https://docs.aerospike.com/reference/configuration#enable-index).",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"enable_idx\",aerospike_sets_enable_index{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\",} or on() vector(-1))",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Stop Writes Size (Unique values)",
   "type": "stat",
   "description": "More details about [stop writes size](https://docs.aerospike.com/reference/configuration#stop-writes-size).",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"stop_write_size\", aerospike_sets_stop_writes_size{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\",} or on() vector(-1))",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "% Set Quota Used (topk)",
   "type": "bargauge",
   "description": "Set Quota usage against \"stop write size\" configuration",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk( $set_quota_topk,sort_desc((\n  (aerospike_sets_memory_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set\",}+aerospike_sets_device_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set\",})\n  /(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set\",}!=0) )*100))",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "topk( $set_quota_topk, sort_desc((\n  (aerospike_sets_data_used_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set\",})\n  /(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set\",}!=0) )*100) )",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Master & Replica Objects (total)",
   "type": "stat",
   "description": "Namespace objects (tombstones, master_objects, prole_objects, evicted_objects)",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_sets_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set|$^\",})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Data used (bytes) ",
   "type": "stat",
   "description": "Displays sum of all device or memory used by data in this set (without index) across selected nodes",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum( aerospike_sets_memory_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\", }\nor\n aerospike_sets_device_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\", })\n",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(aerospike_sets_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\",  ns=~\"$namespace|$^\", set=~\"$set|$^\", })",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Master & Replica Objects",
   "type": "bargauge",
   "description": "Namespace objects (tombstones, master_objects, prole_objects, evicted_objects)",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_sets_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set|$^\",})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_sets_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set|$^\",})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(aerospike_sets_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set|$^\",})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Data used (bytes) ",
   "type": "bargauge",
   "description": "Displays minimum, average and maximum of device or memory used by data in this set (without index) across selected nodes",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min( aerospike_sets_memory_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\", })\nor\n aerospike_sets_device_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\", } \n",
     "legendFormat": "Memory"
    },
    {
     "expr": "avg( aerospike_sets_memory_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\", })\nor\n aerospike_sets_device_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\", } \n",
     "legendFormat": "Avg"
    },
    {
     "expr": "avg( aerospike_sets_memory_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\", })\nor\n aerospike_sets_device_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\", } \n",
     "legendFormat": "Max"
    },
    {
     "expr": "min(aerospike_sets_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\",  ns=~\"$namespace|$^\", set=~\"$set|$^\", })",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_sets_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\",  ns=~\"$namespace|$^\", set=~\"$set|$^\", })",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(aerospike_sets_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\",  ns=~\"$namespace|$^\", set=~\"$set|$^\", })",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "% Set Quota Used ",
   "type": "timeseries",
   "description": "Set Quota usage against \"stop write size\" configuration",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((\n  (aerospike_sets_memory_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set\",}+aerospike_sets_device_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set\",})\n  /(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set\",}!=0) )*100)",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "((\n  (aerospike_sets_data_used_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set\",})\n  /(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", set=~\"$set\",}!=0) )*100) ",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Data used (bytes) ",
   "type": "timeseries",
   "description": "Device and memory for a set. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "( aerospike_sets_memory_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\", })\nor\n aerospike_sets_device_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\", } \n",
     "legendFormat": "{{service}} : Memory"
    },
    {
     "expr": "aerospike_sets_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\",  ns=~\"$namespace|$^\", set=~\"$set|$^\", } ",
     "legendFormat": "{{service}} "
    },
    {
     "expr": "\n aerospike_sets_device_data_bytes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set|$^\" }\n",
     "legendFormat": "{{service}} : Device"
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "aerospike_sets_index_populating{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\",}",
     "legendFormat": "{{service}} : Indexes Populating "
    },
    {
     "expr": "aerospike_sets_sindexes{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\",}",
     "legendFormat": "{{service}} : Secondary Indexes"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aerospike_sets_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\",}",
     "legendFormat": "{{service}}: Master"
    },
    {
     "expr": "aerospike_sets_tombstones{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\",}",
     "legendFormat": "{{service}}: Tombstones"
    },
    {
     "expr": "aerospike_sets_truncate_lut{job=\"$job_name\", cluster_name=~\"$cluster|$^\",  service=~\"$node|$^\", ns=~\"$namespace\", set=~\"$set\",}",
     "legendFormat": "{{service}}: Truncations"
    }
   ]
  }
 ]
}